name: 'Terraform Plan'
description: 'Terraform Compoite action for terraform plan'

inputs:
  DIRECTORY:
    description: 'Working directory'
    required: true
runs:
  using: "composite"
  steps:
    - name: Terraform Plan
      run: cd services/${{inputs.DIRECTORY}} && terraform plan
      shell: bash
