name: 'Terraform Plan'
description: 'Terraform Custom Workflow'

inputs:
  STATEBUCKET:
    description: 'statebucket name'
    required: true
    default: tf-state-bucket1 
  ENVIRONMENT:
    description: 'environment name'
    required: true
    default: test
  REGION:
    description: 'region'
    required: true
    default: "ap-south-1"
env:
  STATEBUCKETNAME: ${{ github.event.inputs.STATEBUCKET }}
#   STATEKEYNAME: ${{ github.event.inputs.STATEKEY }}
#   ENVRIONMENTNAME: ${{ github.event.inputs.ENVRIONMENT }}
  REGIONNAME: ${{ github.event.inputs.REGION }}
runs:
  using: "composite"
  steps:
    - name: Terraform Init
      run: terraform init -backend-config="bucket=${STATEBUCKETNAME}" -backend-config-="region=${REGIONNAME}"
      shell: bash
    - name: Terraform Plan
      run: terraform plan
      shell: bash
