name: 'Terraform Plan'
description: 'Terraform Custom Workflow'

inputs:
  STATEBUCKET:
    description: 'statebucket name'
    required: true
    default: tf-state-bucket1 
  ENVIRONMENT:
    description: 'environment name'
    required: true
    default: test
  REGION:
    description: 'region'
    required: true
    default: "ap-south-1"
runs:
  using: "composite"
  steps:
    - name: Terraform Init
      run: terraform init
      shell: bash
    - name: Terraform Plan
      run: terraform plan
      shell: bash
