name: 'Terraform Plan'
description: 'Terraform Custom Workflow'

inputs:
  STATEBUCKET:
    description: 'statebucket name'
    required: true
    default: tf-state-bucket1 
  ENVIRONMENT:
    description: 'environment name'
    required: true
    default: test
  REGION:
    description: 'region'
    required: true
    default: "ap-south-1"
  DIRECTORY:
    description: 'Working directory'
    required: true
    default: "sqs-s3-event"
runs:
  using: "composite"
  steps:
    - name: Terraform Init
      run: terraform init -backend-config="bucket=${{inputs.STATEBUCKET}}" -backend-config="region=${{inputs.REGION}}"
      shell: bash
      working-directory: ./service/${{inputs.DIRECTORY}}
    - name: Terraform Plan
      run: terraform plan
      shell: bash
