name: 'Terraform Plan'
description: 'Terraform Custom Workflow'

inputs:
  STATE_BUCKET:
    description: 'statebucket name'
    required: true
  ENVIRONMENT:
    description: 'environment name'
    required: true
  REGION:
    description: 'region'
    required: true
  DIRECTORY:
    description: 'Working directory'
    required: true
runs:
  using: "composite"
  steps:
    - name: Terraform Init
      run: cd services/${{inputs.DIRECTORY}} && terraform init -backend-config="bucket=${{inputs.STATE_BUCKET}}" -backend-config="region=${{inputs.REGION}}"
      shell: bash
    - name: Terraform Plan
      run: cd services/${{inputs.DIRECTORY}} && terraform plan
      shell: bash
