name: 'Terraform Plan destroy'
description: 'Terraform Composite action for terrafrom plan destroy'

inputs:
  STATE_BUCKET:
    description: 'statebucket name'
    required: true
  ENVIRONMENT:
    description: 'environment name'
    required: true
  REGION:
    description: 'region'
    required: true
  DIRECTORY:
    description: 'Working directory'
    required: true
runs:
  using: "composite"
  steps:
    - name: Terraform Init
      run: cd ./services/${{inputs.DIRECTORY}} && terraform init -backend-config="bucket=${{inputs.STATE_BUCKET}}" -backend-config="region=${{inputs.REGION}}" && terraform workspace select ${{inputs.ENVIRONMENT}} || terraform workspace new ${{inputs.ENVIRONMENT}}
      shell: bash  
    - name: Terraform Plan Destroy
      run: cd ./services/${{inputs.DIRECTORY}} && terraform plan -destroy
      shell: bash
