name: 'Terraform Plan destroy'
description: 'Terraform Composite action for terrafrom plan destroy'

inputs:
  DIRECTORY:
    description: 'Working directory'
    required: true
runs:
  using: "composite"
  steps:
    - name: Terraform Plan destroy
      run: cd services/${{inputs.DIRECTORY}} && terraform plan -destroy
      shell: bash
