name: 'Terraform Init'
description: 'Terraform Composite action for terrafrom init'

inputs:  
  ENVIRONMENT:
    description: 'environment name'
    required: true
  DIRECTORY:
    description: 'Working directory'
    required: true
runs:
  using: "composite"
  steps:
    - name: Terraform Init
      run: cd ./services/${{inputs.DIRECTORY}} && terraform init -backend-config="bucket=${{inputs.STATE_BUCKET}}" -backend-config="key=${{inputs.STATE_KEY}}" -backend-config="region=${{inputs.REGION}}" -backend-config="dynamodb_table=$(STATE_LOCK_TABLE)" && terraform workspace new ${{inputs.ENVIRONMENT}} || terraform workspace select ${{inputs.ENVIRONMENT}}
      shell: bash
