name: 'Terraform destroy'
description: 'Terraform Composite action for terrafrom destroy'

inputs:
  DIRECTORY:
    description: 'Working directory'
    required: true
runs:
  using: "composite"
  steps:
    - name: Terraform Destroy
      run: cd ./services/${{inputs.DIRECTORY}} && terraform destroy -auto-approve
      shell: bash
