name: 'Terraform Apply'
description: 'Terraform Composite action for terrafrom apply'

inputs:
  DIRECTORY:
    description: 'Working directory'
    required: true
runs:
  using: "composite"
  steps:
    - name: Terraform Apply
      run: cd ./services/${{inputs.DIRECTORY}} && terraform apply -auto-approve
      shell: bash
